server:
  #声明服务的端口
  port: 7001
eureka:
    #如果这里配置成空
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
    service-url:
      #设置服务注册中心的URL，用于client和server端交流，单机情况配成当前eureka服务的端口（7001）也可以
      defaultZone: http://localhost:7900/eureka/
